### ISSUE TITLE
Tag Search Option

### ISSUE THREAD

**Issue by CharaViolet** [AprilSylph/Vision#14]
Many like the option of having the search bar lead to a tag search rather than a normal search, it would be very cool to see this as an option...

(or if not, does anyone at least know how to custom add it in the html?)

**Comment by AprilSylph** [comment]
Changing the behaviour of the search form is not something I'm interested in doing, and implementing such a feature would require additional Javascript which would make the experience inconsistent for those with Javascript disabled.

I do not recommend modifying the theme HTML, as doing so will prevent you from receiving updates for Vision. If you wish to add the feature for just your blog, you can add this to the Widget Code field to do so:

```html
<script>
document.getElementById('search').addEventListener('submit', event => {
  event.preventDefault();
  const { value } = event.currentTarget.children['q'];
  location.assign(`/tagged/${value}`);
});
</script>
```
