### ISSUE TITLE
Anytime I try to edit the appearance of my blog it gives me an error and I cannot save the edits

### ISSUE THREAD

**Issue by Lanomin** [AprilSylph/Vision#25]
So I install the theme and it works great, but the issue is when I try to edit my blog from the 'edit appearance' menu, any time i try to change something like the background color, avatar shape, text color, or anything, and go to save the changes I get an error that says 'HTML tags are not allowed in custom CSS code'. I'm not touching the code at all, only messing with the appearance editor. I was using a custom theme before this, and it looks like my background color choice has been carried over, so I'm not sure if that might be causing any potential issues? No idea, but if you have any suggestions on how to fix this I'd really appreciate it, I'd love to be able to use this for my blog but I currently have a bright blue bg with pink text links, it looks pretty obnoxious and I'd like to make it less of an eyestrain haha. I have some pics of what it looks like for when I try to change stuff in the appearance menu and also the error. 

![changing color of blog](https://github.com/user-attachments/assets/3329e3df-b70d-4d45-9fa8-85dc4964ff89)
![default blog that works ](https://github.com/user-attachments/assets/580c49ab-ed18-466f-a4ee-67c3a3eedb54)
![error after changing color](https://github.com/user-attachments/assets/1fc23039-ac08-418e-93ae-479855d6dcd9)

**Comment by AprilSylph** [comment]
You need to remove any invalid CSS from "Advanced options" &rarr; "Add custom CSS".

Also, this is not a theme issue.

**Comment by Lanomin** [comment]
Thank you, this did fix it. I'm sorry for the dumb question and putting my
question as an issue with the theme, the theme works and looks great. I
really appreciate your help, thank you again.
